### ISSUE TITLE
nvidia driver nvlddmkm 391.35

### ISSUE THREAD

**Issue by toddfraser88** [MovAX0xDEAD/NTOSKRNL_Emu#1]
I'd like to test if the main nvidia driver sys file nvlddmkm.sys will load with this extender but some functions are still missing from the extender

these are

MmAllocatePagesForMdlEx
KeInvalidateAllCaches
RtlCmDecodeMemIoResource
KeInitializeThreadedDpc
wcscpy_s
CmRegisterCallbackEx
PsSetCreateProcessNotifyRoutineEx
strncpy_s
ExInitializeLookasideListEx
ExDeleteLookasideListEx

could you add some stub functions for these to the extender so I can test if the driver loads?

there is also in ksecdd.sys - not sure how to resolve this

BCryptGenRandom

**Comment by MovAX0xDEAD** [comment]
**toddfraser88**,
Currently I dont plan to implement these functions, maybe later

**Comment by toddfraser88** [comment]
how about VMWare's 3D driver? - it's only missing 2 functions

MmAllocatePagesForMdlEx
RtlCmDecodeMemIoResource

or not at the moment?

**Comment by MovAX0xDEAD** [comment]
**toddfraser88**,
3D driver may require all graphic/dxapi/win32k/... subsystem from new "kernels", i need to check what it may required besides two import functions

**Comment by MovAX0xDEAD** [comment]
There is no point to use "vista display model" drivers in xp/w2003 even with import functions match, they will need DirectX Kernel support, not existing on pre-Vista OSes
