### ISSUE TITLE
Compiling For Windows XP x64?

### ISSUE THREAD

**Issue by Legendary-Candice-Joe** [MovAX0xDEAD/NTOSKRNL_Emu#10]
I followed the instructions and indeed got it to compile, but I noticed that there is no way of compiling to Windows XP x64.
The only xp machine that I have has x64 and it can't run 32bit drivers.

Is there anyway of compiling for x64? Am I missing something?
Or is it simply not possible?

**Comment by the-r3dacted** [comment]
XP x64 is the same as Server 2003 x64, or wnet or whatever the output dir is for 2003.

**Comment by Legendary-Candice-Joe** [comment]
That worked. But the driver I'm trying to install on XP, is saying "The specified location does not contain a software driver for your device." It is XP64 and the driver itself is 64-bit. I'm not sure If I should patch the driver, or if there's a way to bypass it entirely. But I just can't get the driver to install.

Not sure if this counts as an entirely separate issue but whatever.

**Comment by the-r3dacted** [comment]
You probably have to use the Have Disk option. If you currently are, the INF is probably specifying NT6 or later, which can be removed. Find NTamd64.6.x in the INF, and remove .6.x in all instances of it in the INF.

**Comment by Legendary-Candice-Joe** [comment]
Last question:

Will this amd display driver work? I'm sure that this project was designed for smaller drivers but I wanted to try it with one of my small amd graphics cards. I installed the driver, I hex-edited it so it uses ntoskrn8.sys. But the driver still fails. I'm not sure if it will work. If it is impossible (wouldn't be suprised lol) then I will just close the thread.

**Comment by the-r3dacted** [comment]
It's impossible. You can't port a Vista+ driver to XP, at least easily. XP has XPDM, kernel mode drivers, while Vista+ has WDDM, user mode drivers.

**Comment by Legendary-Candice-Joe** [comment]
Well can't say that was unexpected.

Eitherway, super helpful. tysm.
