### ISSUE TITLE
[SUGGESTION] ReactOS as codebase

### ISSUE THREAD

**Issue by MarcoRavich** [MovAX0xDEAD/NTOSKRNL_Emu#12]
Hi there, this is a really cool project !

Given that I am NOT a developer (much less a Kernel one), couldn't @ReactOS core components be - dunno if easily - "ported" instead of re-implement everything from scratch?

https://reactos.org/

Keep also in consideration to establish some kind of collaboration with other open projects such as: 
- @kika123's - dated - [ReactOS Core](https://github.com/kika123/roscore#readme);
- @themirrazz's [React96](https://github.com/themirrazz/react96#readme);
- @dz333n's [ReactOS Kernel](https://github.com/dz333n/ReactOS-Kernel#readme).

Last but not least, check out my Opendows (to replace - legacy ? - Windows components with open source counterparts) project: https://forart.it/opendows

Hope that inspires !

**Comment by GeorgeK1ng** [comment]
We don’t care about ReactOS. If you wanna use that mix, use OneCoreApi.
