### ISSUE TITLE
Patched Binaries

### ISSUE THREAD

**Issue by LuxLOL** [MovAX0xDEAD/NTOSKRNL_Emu#2]
Hi,
Would it be possible to also upload all the patched Binaries for the WDF, USB3/UASP, StorAHCI, NVMe, MSAHCI, StorPort?

**Comment by MovAX0xDEAD** [comment]
Hi LuxLOL,

I dont publish patched MS binaries, try to prepare files yourself

**Comment by LuxLOL** [comment]
It doesn't help if the Guide only tells people what to change but not HOW to change it.
