### ISSUE TITLE
error - cannot open compiler generated file

### ISSUE THREAD

**Issue by toddfraser88** [MovAX0xDEAD/NTOSKRNL_Emu#3]
I am getting this error trying to compile most recent commit

\crt.c : error C1083: Cannot open compiler generated file: 'asm/crt.asm': No such file or directory

**Comment by MovAX0xDEAD** [comment]
Hi **toddfraser88**

Thanks for report, empty folders was not synced with github repository

To fix:
- fetch commit  https://github.com/MovAX0xDEAD/NTOSKRNL_Emu/commit/1dbf56054e6720427cdc58f2537075bfc288bc49
- or create subfolders manualy  ntoskrn8/**asm**/  +  storpor8/**asm**/

**Comment by toddfraser88** [comment]
Thanks!
