### ISSUE TITLE
Can you transplant basicdisplay.sys to winvista and 7,to make aero enabled without video card driver

### ISSUE THREAD

**Issue by wyf180** [MovAX0xDEAD/NTOSKRNL_Emu#4]
Some old pcs can install win7 or vista ,but can't show aero because of lack of video card driver.So can you transplant basicdisplay.sys driver to these old system to make them show aero without video card driver?

**Comment by iyutr** [comment]
The switch of turning-off the video-acceleration is in DWM.exe. Untill now perfect patch is not invented.
It is needed to make that a varible "CompositionEnabledByPolicy" be always = 1. More about it:
https://www.win-raid.com/t4035f45-Windows-XP-Bit-and-Server-Bit-on-Modern-Hardware-268.html#msg102174

Disassembling with symbols: 


![d1z](https://user-images.githubusercontent.com/47095941/103465094-55a4aa80-4d41-11eb-9faa-5a64f762d19a.png)


![d2z](https://user-images.githubusercontent.com/47095941/103465098-59d0c800-4d41-11eb-9ca0-2215e753d619.png)

**Comment by MovAX0xDEAD** [comment]
Windows 7 things not related to project
