### ISSUE TITLE
Windows 2000 question

### ISSUE THREAD

**Issue by Daniel7689** [MovAX0xDEAD/NTOSKRNL_Emu#6]
Is it possible to use this to get the Windows 8 AHCI driver to work on 2000?

**Comment by MollySpacefield** [comment]
it better fucking have support for win2k, it better

**Comment by MovAX0xDEAD** [comment]
> Is it possible to use this to get the Windows 8 AHCI driver to work on 2000?
I think No, project designed to work with XP/2000 kernel headers/exports
